from flask import Flask, render_template, request
import sqlalchemy
import pandas as pd
import pymysql
from datetime import date, time, datetime, time     
from openpyxl import Workbook, load_workbook
import time
import pywhatkit
app=Flask(__name__,template_folder='../templates')
@app.route('/')
def home():
    return render_template('homepage.html')   
@app.route('/login.html')
def login():
    return render_template('login.html')   
@app.route('/Menu.html',methods=["POST"])
def menu():
    if request.method =='POST':
     usuario=request.form["Usuario"] 
     senha=request.form["Senha"]
    if usuario == "Testeteste" and senha =="12345" or usuario == "teste" and senha =="45678":
     return render_template('Menu.html')
    else:
     return render_template("cadastroerrado.html")  
@app.route('/cadastro.html')
def cadastro():
    return render_template("cadastro.html")
@app.route('/addcadastro',methods=["POST"])
def addcadastro(): 
    if request.method =='POST':
        nome=request.form['Nome'],
        telefone=request.form['Telefone'],
        email=request.form['Email'],
        vendedor=request.form['Vendedor'],
        hoje= date.today()
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/crm")
        df= pd.read_sql_table("cadastro", engine)
        query=f'''
        INSERT INTO cadastro 
        (nome, telefone, atendimento,email, vendedor)
        VALUES 
        ('{nome}','+55{telefone}','{hoje}', '{email}', '{vendedor}');
        '''
        df1=pd.read_sql_query(query, engine)
@app.route('/Mensagem.html')
def Mensagem():
    return render_template("Mensagem.html")
@app.route("/Hoje.html")
def Hoje():
    return render_template("Hoje.html")

    if request.method =='POST':
        Textohoje=request.form['Textohoje']
@app.route("/mensagemhoje",methods=["POST"])
def mensagemhoje():
    if request.method =='POST':
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/crm")
        df= pd.read_sql_table("cadastro", engine)
        Textohoje=request.form['Textohoje']
        df= pd.read_sql_table("cadastro", engine)
        queryhoje=f'''   
            select nome, telefone from cadastro
            where atendimento = subdate(current_date,0)

                '''
        df= pd.read_sql_table("cadastro", engine)
        df2=pd.read_sql_query(queryhoje, engine)
        df2.to_excel("Hoje.xlsx")
        wb = load_workbook('Hoje.xlsx')
        ws = wb.active
        A=ws['c2'].value
        B=ws['C3'].value
        C=ws['C3'].value
        D=ws['c4'].value
        E=ws['c5'].value
        F=ws['c6'].value
        G=ws['C7'].value
        H=ws['C8'].value
        I=ws['c9'].value
        J=ws['c10'].value
        K=ws['c11'].value
        L=ws['C12'].value
        M=ws['C13'].value
        N=ws['c14'].value
        O=ws['c15'].value
        P=ws['c16'].value
        Q=ws['C17'].value
        R=ws['C18'].value
        S=ws['c19'].value
        T=ws['c20'].value
        U=ws['c21'].value
        V=ws['C22'].value
        W=ws['C23'].value
        X=ws['c24'].value
        Y=ws['c25'].value
        Z=ws['c26'].value
        AA=ws['C27'].value
        AB=ws['C28'].value
        AC=ws['c29'].value
        AD=ws['c30'].value
        AE=ws['c31'].value
        AF=ws['C32'].value
        AG=ws['C33'].value
        AH=ws['c34'].value
        AI=ws['c35'].value
        AJ=ws['c36'].value
        AK=ws['C37'].value
        AL=ws['C38'].value
        AM=ws['c39'].value
        AN=ws['c40'].value
        AO=ws['c41'].value
        AP=ws['C42'].value
        AQ=ws['C43'].value
        AR=ws['c44'].value
        AS=ws['c45'].value
        AT=ws['c46'].value
        AU=ws['C47'].value
        AV=ws['C48'].value
        AW=ws['c49'].value
        AX=ws['c50'].value
        AY=ws['c51'].value
        AZ=ws['C52'].value
        AAA=ws['C53'].value
        ABA=ws['c54'].value
        ACA=ws['c55'].value
        ADA=ws['c56'].value
        AEA=ws['C57'].value
        AFA=ws['C58'].value
        AGA=ws['c59'].value
        AHA=ws['c60'].value
        AIA=ws['c61'].value
        AJA=ws['C62'].value
        AKA=ws['C63'].value
        ALA=ws['c64'].value
        AMA=ws['c55'].value
        ANA=ws['c66'].value
        AOA=ws['C67'].value
        APA=ws['C68'].value
        AQA=ws['c69'].value
        ARA=ws['c70'].value
        ASA=ws['c71'].value
        ATA=ws['C72'].value
        AUA=ws['C73'].value
        AVA=ws['c74'].value
        AWA=ws['c75'].value
        AXA=ws['c76'].value
        AYA=ws['C77'].value
        AZA=ws['C78'].value
        AAB=ws['c79'].value
        AAC=ws['c80'].value
        AAD=ws['c81'].value
        AAE=ws['C82'].value
        AAF=ws['C83'].value
        AAG=ws['c84'].value
        AAH=ws['c85'].value
        AAI=ws['c86'].value
        AAJ=ws['C87'].value
        AAK=ws['C88'].value
        AAL=ws['c89'].value
        AAM=ws['c90'].value
        AAN=ws['c91'].value
        AAO=ws['C92'].value
        AAP=ws['C93'].value
        AAQ=ws['c94'].value
        AAR=ws['c95'].value
        AAS=ws['c96'].value
        AAT=ws['C97'].value
        AAU=ws['C98'].value
        AAV=ws['c99'].value
        AAY=ws['c100'].value
        pywhatkit.sendwhatmsg_instantly(A,Textohoje)
        pywhatkit.sendwhatmsg_instantly(B,Textohoje)
        pywhatkit.sendwhatmsg_instantly(C,Textoontem)
        pywhatkit.sendwhatmsg_instantly(D,Textoontem)
        pywhatkit.sendwhatmsg_instantly(E,Textoontem)
        pywhatkit.sendwhatmsg_instantly(F,Textoontem)
        pywhatkit.sendwhatmsg_instantly(G,Textoontem)
        pywhatkit.sendwhatmsg_instantly(H,Textoontem)
        pywhatkit.sendwhatmsg_instantly(I,Textoontem)
        pywhatkit.sendwhatmsg_instantly(J,Textoontem)
        pywhatkit.sendwhatmsg_instantly(K,Textoontem)
        pywhatkit.sendwhatmsg_instantly(L,Textoontem)
        pywhatkit.sendwhatmsg_instantly(M,Textoontem)
        pywhatkit.sendwhatmsg_instantly(N,Textoontem)
        pywhatkit.sendwhatmsg_instantly(O,Textoontem)
        pywhatkit.sendwhatmsg_instantly(P,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Q,Textoontem)
        pywhatkit.sendwhatmsg_instantly(R,Textoontem)
        pywhatkit.sendwhatmsg_instantly(S,Textoontem)
        pywhatkit.sendwhatmsg_instantly(T,Textoontem)
        pywhatkit.sendwhatmsg_instantly(U,Textoontem)
        pywhatkit.sendwhatmsg_instantly(V,Textoontem)
        pywhatkit.sendwhatmsg_instantly(W,Textoontem)
        pywhatkit.sendwhatmsg_instantly(X,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Z,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AL,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AM,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AN,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AO,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AP,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ABA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AHA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AIA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AKA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ALA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AMA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ANA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AOA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(APA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ARA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ASA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ATA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AUA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AVA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AWA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AXA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AYA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAX,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAZ,Textoontem)            
@app.route("/Ontem.html")
def Ontem():
    return render_template("Ontem.html")
@app.route("/mensagemontem", methods=["POST"])
def mensagontem():
    engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/crm")
    Textoontem=request.form['Textoontem']
    queryontem=f'''   
        select nome, telefone from cadastro
        where atendimento = subdate(current_date,7)

            '''
    df= pd.read_sql_table("cadastro", engine)
    df2=pd.read_sql_query(queryontem, engine)
    df2.to_excel("ontem.xlsx")
    wb = load_workbook('ontem.xlsx')
    ws = wb.active
    A=ws['c2'].value
    B=ws['C3'].value
    C=ws['C3'].value
    D=ws['c4'].value
    E=ws['c5'].value
    F=ws['c6'].value
    G=ws['C7'].value
    H=ws['C8'].value
    I=ws['c9'].value
    J=ws['c10'].value
    K=ws['c11'].value
    L=ws['C12'].value
    M=ws['C13'].value
    N=ws['c14'].value
    O=ws['c15'].value
    P=ws['c16'].value
    Q=ws['C17'].value
    R=ws['C18'].value
    S=ws['c19'].value
    T=ws['c20'].value
    U=ws['c21'].value
    V=ws['C22'].value
    W=ws['C23'].value
    X=ws['c24'].value
    Y=ws['c25'].value
    Z=ws['c26'].value
    AA=ws['C27'].value
    AB=ws['C28'].value
    AC=ws['c29'].value
    AD=ws['c30'].value
    AE=ws['c31'].value
    AF=ws['C32'].value
    AG=ws['C33'].value
    AH=ws['c34'].value
    AI=ws['c35'].value
    AJ=ws['c36'].value
    AK=ws['C37'].value
    AL=ws['C38'].value
    AM=ws['c39'].value
    AN=ws['c40'].value
    AO=ws['c41'].value
    AP=ws['C42'].value
    AQ=ws['C43'].value
    AR=ws['c44'].value
    AS=ws['c45'].value
    AT=ws['c46'].value
    AU=ws['C47'].value
    AV=ws['C48'].value
    AW=ws['c49'].value
    AX=ws['c50'].value
    AY=ws['c51'].value
    AZ=ws['C52'].value
    AAA=ws['C53'].value
    ABA=ws['c54'].value
    ACA=ws['c55'].value
    ADA=ws['c56'].value
    AEA=ws['C57'].value
    AFA=ws['C58'].value
    AGA=ws['c59'].value
    AHA=ws['c60'].value
    AIA=ws['c61'].value
    AJA=ws['C62'].value
    AKA=ws['C63'].value
    ALA=ws['c64'].value
    AMA=ws['c55'].value
    ANA=ws['c66'].value
    AOA=ws['C67'].value
    APA=ws['C68'].value
    AQA=ws['c69'].value
    ARA=ws['c70'].value
    ASA=ws['c71'].value
    ATA=ws['C72'].value
    AUA=ws['C73'].value
    AVA=ws['c74'].value
    AWA=ws['c75'].value
    AXA=ws['c76'].value
    AYA=ws['C77'].value
    AZA=ws['C78'].value
    AAB=ws['c79'].value
    AAC=ws['c80'].value
    AAD=ws['c81'].value
    AAE=ws['C82'].value
    AAF=ws['C83'].value
    AAG=ws['c84'].value
    AAH=ws['c85'].value
    AAI=ws['c86'].value
    AAJ=ws['C87'].value
    AAK=ws['C88'].value
    AAL=ws['c89'].value
    AAM=ws['c90'].value
    AAN=ws['c91'].value
    AAO=ws['C92'].value
    AAP=ws['C93'].value
    AAQ=ws['c94'].value
    AAR=ws['c95'].value
    AAS=ws['c96'].value
    AAT=ws['C97'].value
    AAU=ws['C98'].value
    AAV=ws['c99'].value
    AAY=ws['c100'].value
    pywhatkit.sendwhatmsg_instantly(A,Textoontem)
    pywhatkit.sendwhatmsg_instantly(B,Textoontem)
    pywhatkit.sendwhatmsg_instantly(C,Textoontem)
    pywhatkit.sendwhatmsg_instantly(D,Textoontem)
    pywhatkit.sendwhatmsg_instantly(E,Textoontem)
    pywhatkit.sendwhatmsg_instantly(F,Textoontem)
    pywhatkit.sendwhatmsg_instantly(G,Textoontem)
    pywhatkit.sendwhatmsg_instantly(H,Textoontem)
    pywhatkit.sendwhatmsg_instantly(I,Textoontem)
    pywhatkit.sendwhatmsg_instantly(J,Textoontem)
    pywhatkit.sendwhatmsg_instantly(K,Textoontem)
    pywhatkit.sendwhatmsg_instantly(L,Textoontem)
    pywhatkit.sendwhatmsg_instantly(M,Textoontem)
    pywhatkit.sendwhatmsg_instantly(N,Textoontem)
    pywhatkit.sendwhatmsg_instantly(O,Textoontem)
    pywhatkit.sendwhatmsg_instantly(P,Textoontem)
    pywhatkit.sendwhatmsg_instantly(Q,Textoontem)
    pywhatkit.sendwhatmsg_instantly(R,Textoontem)
    pywhatkit.sendwhatmsg_instantly(S,Textoontem)
    pywhatkit.sendwhatmsg_instantly(T,Textoontem)
    pywhatkit.sendwhatmsg_instantly(U,Textoontem)
    pywhatkit.sendwhatmsg_instantly(V,Textoontem)
    pywhatkit.sendwhatmsg_instantly(W,Textoontem)
    pywhatkit.sendwhatmsg_instantly(X,Textoontem)
    pywhatkit.sendwhatmsg_instantly(Z,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AB,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AC,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AD,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AE,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AF,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AG,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AH,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AI,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AJ,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AK,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AL,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AM,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AN,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AO,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AP,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AQ,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AR,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AS,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AT,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AU,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AV,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AW,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AY,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AZ,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ABA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AHA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AIA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AJA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AKA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ALA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AMA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ANA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AOA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(APA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AQA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ARA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ASA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(ATA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AUA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AVA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AWA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AXA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AYA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AZA,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAB,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAC,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAD,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAE,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAF,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAG,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAH,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAI,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAJ,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAK,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAR,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAS,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAT,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAU,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAV,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAW,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAX,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAY,Textoontem)
    pywhatkit.sendwhatmsg_instantly(AAZ,Textoontem)
@app.route("/7dia.html")
def setedia():
  return render_template("7dia.html")
@app.route('/mensagem7',methods=["POST"])
def envio7():
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/crm")
        Textoontem=request.form['Textoontem']
        queryontem=f'''   
            select nome, telefone from cadastro
            where atendimento = subdate(current_date,1)

                '''
        df= pd.read_sql_table("cadastro", engine)
        df2=pd.read_sql_query(queryontem, engine)
        df2.to_excel("ontem.xlsx")
        wb = load_workbook('ontem.xlsx')
        ws = wb.active
        A=ws['c2'].value
        B=ws['C3'].value
        C=ws['C3'].value
        D=ws['c4'].value
        E=ws['c5'].value
        F=ws['c6'].value
        G=ws['C7'].value
        H=ws['C8'].value
        I=ws['c9'].value
        J=ws['c10'].value
        K=ws['c11'].value
        L=ws['C12'].value
        M=ws['C13'].value
        N=ws['c14'].value
        O=ws['c15'].value
        P=ws['c16'].value
        Q=ws['C17'].value
        R=ws['C18'].value
        S=ws['c19'].value
        T=ws['c20'].value
        U=ws['c21'].value
        V=ws['C22'].value
        W=ws['C23'].value
        X=ws['c24'].value
        Y=ws['c25'].value
        Z=ws['c26'].value
        AA=ws['C27'].value
        AB=ws['C28'].value
        AC=ws['c29'].value
        AD=ws['c30'].value
        AE=ws['c31'].value
        AF=ws['C32'].value
        AG=ws['C33'].value
        AH=ws['c34'].value
        AI=ws['c35'].value
        AJ=ws['c36'].value
        AK=ws['C37'].value
        AL=ws['C38'].value
        AM=ws['c39'].value
        AN=ws['c40'].value
        AO=ws['c41'].value
        AP=ws['C42'].value
        AQ=ws['C43'].value
        AR=ws['c44'].value
        AS=ws['c45'].value
        AT=ws['c46'].value
        AU=ws['C47'].value
        AV=ws['C48'].value
        AW=ws['c49'].value
        AX=ws['c50'].value
        AY=ws['c51'].value
        AZ=ws['C52'].value
        AAA=ws['C53'].value
        ABA=ws['c54'].value
        ACA=ws['c55'].value
        ADA=ws['c56'].value
        AEA=ws['C57'].value
        AFA=ws['C58'].value
        AGA=ws['c59'].value
        AHA=ws['c60'].value
        AIA=ws['c61'].value
        AJA=ws['C62'].value
        AKA=ws['C63'].value
        ALA=ws['c64'].value
        AMA=ws['c55'].value
        ANA=ws['c66'].value
        AOA=ws['C67'].value
        APA=ws['C68'].value
        AQA=ws['c69'].value
        ARA=ws['c70'].value
        ASA=ws['c71'].value
        ATA=ws['C72'].value
        AUA=ws['C73'].value
        AVA=ws['c74'].value
        AWA=ws['c75'].value
        AXA=ws['c76'].value
        AYA=ws['C77'].value
        AZA=ws['C78'].value
        AAB=ws['c79'].value
        AAC=ws['c80'].value
        AAD=ws['c81'].value
        AAE=ws['C82'].value
        AAF=ws['C83'].value
        AAG=ws['c84'].value
        AAH=ws['c85'].value
        AAI=ws['c86'].value
        AAJ=ws['C87'].value
        AAK=ws['C88'].value
        AAL=ws['c89'].value
        AAM=ws['c90'].value
        AAN=ws['c91'].value
        AAO=ws['C92'].value
        AAP=ws['C93'].value
        AAQ=ws['c94'].value
        AAR=ws['c95'].value
        AAS=ws['c96'].value
        AAT=ws['C97'].value
        AAU=ws['C98'].value
        AAV=ws['c99'].value
        AAY=ws['c100'].value
        pywhatkit.sendwhatmsg_instantly(A,Textoontem)
        pywhatkit.sendwhatmsg_instantly(B,Textoontem)
        pywhatkit.sendwhatmsg_instantly(C,Textoontem)
        pywhatkit.sendwhatmsg_instantly(D,Textoontem)
        pywhatkit.sendwhatmsg_instantly(E,Textoontem)
        pywhatkit.sendwhatmsg_instantly(F,Textoontem)
        pywhatkit.sendwhatmsg_instantly(G,Textoontem)
        pywhatkit.sendwhatmsg_instantly(H,Textoontem)
        pywhatkit.sendwhatmsg_instantly(I,Textoontem)
        pywhatkit.sendwhatmsg_instantly(J,Textoontem)
        pywhatkit.sendwhatmsg_instantly(K,Textoontem)
        pywhatkit.sendwhatmsg_instantly(L,Textoontem)
        pywhatkit.sendwhatmsg_instantly(M,Textoontem)
        pywhatkit.sendwhatmsg_instantly(N,Textoontem)
        pywhatkit.sendwhatmsg_instantly(O,Textoontem)
        pywhatkit.sendwhatmsg_instantly(P,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Q,Textoontem)
        pywhatkit.sendwhatmsg_instantly(R,Textoontem)
        pywhatkit.sendwhatmsg_instantly(S,Textoontem)
        pywhatkit.sendwhatmsg_instantly(T,Textoontem)
        pywhatkit.sendwhatmsg_instantly(U,Textoontem)
        pywhatkit.sendwhatmsg_instantly(V,Textoontem)
        pywhatkit.sendwhatmsg_instantly(W,Textoontem)
        pywhatkit.sendwhatmsg_instantly(X,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Z,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AL,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AM,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AN,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AO,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AP,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ABA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AHA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AIA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AKA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ALA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AMA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ANA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AOA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(APA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ARA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ASA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ATA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AUA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AVA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AWA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AXA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AYA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAX,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAZ,Textoontem)
@app.route("/13dia.html")
def trezedia():
    return render_template("13dia.html")
@app.route('/mensagem13',methods=["POST"])
def envio13():
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/crm")
        Textoontem=request.form['Textoontem']
        queryontem=f'''   
            select nome, telefone from cadastro
            where atendimento = subdate(current_date,13)

                '''
        df= pd.read_sql_table("cadastro", engine)
        df2=pd.read_sql_query(queryontem, engine)
        df2.to_excel("ontem.xlsx")
        wb = load_workbook('ontem.xlsx')
        ws = wb.active
        A=ws['c2'].value
        B=ws['C3'].value
        C=ws['C3'].value
        D=ws['c4'].value
        E=ws['c5'].value
        F=ws['c6'].value
        G=ws['C7'].value
        H=ws['C8'].value
        I=ws['c9'].value
        J=ws['c10'].value
        K=ws['c11'].value
        L=ws['C12'].value
        M=ws['C13'].value
        N=ws['c14'].value
        O=ws['c15'].value
        P=ws['c16'].value
        Q=ws['C17'].value
        R=ws['C18'].value
        S=ws['c19'].value
        T=ws['c20'].value
        U=ws['c21'].value
        V=ws['C22'].value
        W=ws['C23'].value
        X=ws['c24'].value
        Y=ws['c25'].value
        Z=ws['c26'].value
        AA=ws['C27'].value
        AB=ws['C28'].value
        AC=ws['c29'].value
        AD=ws['c30'].value
        AE=ws['c31'].value
        AF=ws['C32'].value
        AG=ws['C33'].value
        AH=ws['c34'].value
        AI=ws['c35'].value
        AJ=ws['c36'].value
        AK=ws['C37'].value
        AL=ws['C38'].value
        AM=ws['c39'].value
        AN=ws['c40'].value
        AO=ws['c41'].value
        AP=ws['C42'].value
        AQ=ws['C43'].value
        AR=ws['c44'].value
        AS=ws['c45'].value
        AT=ws['c46'].value
        AU=ws['C47'].value
        AV=ws['C48'].value
        AW=ws['c49'].value
        AX=ws['c50'].value
        AY=ws['c51'].value
        AZ=ws['C52'].value
        AAA=ws['C53'].value
        ABA=ws['c54'].value
        ACA=ws['c55'].value
        ADA=ws['c56'].value
        AEA=ws['C57'].value
        AFA=ws['C58'].value
        AGA=ws['c59'].value
        AHA=ws['c60'].value
        AIA=ws['c61'].value
        AJA=ws['C62'].value
        AKA=ws['C63'].value
        ALA=ws['c64'].value
        AMA=ws['c55'].value
        ANA=ws['c66'].value
        AOA=ws['C67'].value
        APA=ws['C68'].value
        AQA=ws['c69'].value
        ARA=ws['c70'].value
        ASA=ws['c71'].value
        ATA=ws['C72'].value
        AUA=ws['C73'].value
        AVA=ws['c74'].value
        AWA=ws['c75'].value
        AXA=ws['c76'].value
        AYA=ws['C77'].value
        AZA=ws['C78'].value
        AAB=ws['c79'].value
        AAC=ws['c80'].value
        AAD=ws['c81'].value
        AAE=ws['C82'].value
        AAF=ws['C83'].value
        AAG=ws['c84'].value
        AAH=ws['c85'].value
        AAI=ws['c86'].value
        AAJ=ws['C87'].value
        AAK=ws['C88'].value
        AAL=ws['c89'].value
        AAM=ws['c90'].value
        AAN=ws['c91'].value
        AAO=ws['C92'].value
        AAP=ws['C93'].value
        AAQ=ws['c94'].value
        AAR=ws['c95'].value
        AAS=ws['c96'].value
        AAT=ws['C97'].value
        AAU=ws['C98'].value
        AAV=ws['c99'].value
        AAY=ws['c100'].value
        pywhatkit.sendwhatmsg_instantly(A,Textoontem)
        pywhatkit.sendwhatmsg_instantly(B,Textoontem)
        pywhatkit.sendwhatmsg_instantly(C,Textoontem)
        pywhatkit.sendwhatmsg_instantly(D,Textoontem)
        pywhatkit.sendwhatmsg_instantly(E,Textoontem)
        pywhatkit.sendwhatmsg_instantly(F,Textoontem)
        pywhatkit.sendwhatmsg_instantly(G,Textoontem)
        pywhatkit.sendwhatmsg_instantly(H,Textoontem)
        pywhatkit.sendwhatmsg_instantly(I,Textoontem)
        pywhatkit.sendwhatmsg_instantly(J,Textoontem)
        pywhatkit.sendwhatmsg_instantly(K,Textoontem)
        pywhatkit.sendwhatmsg_instantly(L,Textoontem)
        pywhatkit.sendwhatmsg_instantly(M,Textoontem)
        pywhatkit.sendwhatmsg_instantly(N,Textoontem)
        pywhatkit.sendwhatmsg_instantly(O,Textoontem)
        pywhatkit.sendwhatmsg_instantly(P,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Q,Textoontem)
        pywhatkit.sendwhatmsg_instantly(R,Textoontem)
        pywhatkit.sendwhatmsg_instantly(S,Textoontem)
        pywhatkit.sendwhatmsg_instantly(T,Textoontem)
        pywhatkit.sendwhatmsg_instantly(U,Textoontem)
        pywhatkit.sendwhatmsg_instantly(V,Textoontem)
        pywhatkit.sendwhatmsg_instantly(W,Textoontem)
        pywhatkit.sendwhatmsg_instantly(X,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Z,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AL,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AM,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AN,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AO,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AP,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ABA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AHA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AIA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AKA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ALA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AMA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ANA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AOA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(APA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ARA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ASA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ATA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AUA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AVA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AWA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AXA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AYA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAX,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAZ,Textoontem)
@app.route("/enviorapido.html")
def mensagemrapida():
    return render_template("enviorapido.html")
@app.route('/addrapido',methods=["POST"])
def addrapido(): 
    if request.method =='POST':
        nome=request.form["Nome"]
        telefone=request.form["Telefone"]
        hoje= date.today()
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/inicial")
        df= pd.read_sql_table("mensagemrapida", engine)
        query=f'''
            INSERT INTO mensagemrapida 
            (nome, telefone, atendimento)
            VALUES 
            ('{nome}','+55{telefone}','{hoje}');
            '''
        df1=pd.read_sql_query(query, engine)
@app.route("/msgrapido",methods=["POST"])
def msgrapido():
    if request.method =='POST':
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/inicial")
        Textoontem=request.form["Textorapido"]
        df= pd.read_sql_table("mensagemrapida", engine)
        queryhoje=f'''   
            select nome, telefone from mensagemrapida
            where atendimento = subdate(current_date,0)

                '''
        df2=pd.read_sql_query(queryhoje, engine)
        df2.to_excel("Hoje.xlsx")
        wb = load_workbook('Hoje.xlsx')
        ws = wb.active
        A=ws['c2'].value
        B=ws['C3'].value
        C=ws['C3'].value
        D=ws['c4'].value
        E=ws['c5'].value
        F=ws['c6'].value
        G=ws['C7'].value
        H=ws['C8'].value
        I=ws['c9'].value
        J=ws['c10'].value
        K=ws['c11'].value
        L=ws['C12'].value
        M=ws['C13'].value
        N=ws['c14'].value
        O=ws['c15'].value
        P=ws['c16'].value
        Q=ws['C17'].value
        R=ws['C18'].value
        S=ws['c19'].value
        T=ws['c20'].value
        U=ws['c21'].value
        V=ws['C22'].value
        W=ws['C23'].value
        X=ws['c24'].value
        Y=ws['c25'].value
        Z=ws['c26'].value
        AA=ws['C27'].value
        AB=ws['C28'].value
        AC=ws['c29'].value
        AD=ws['c30'].value
        AE=ws['c31'].value
        AF=ws['C32'].value
        AG=ws['C33'].value
        AH=ws['c34'].value
        AI=ws['c35'].value
        AJ=ws['c36'].value
        AK=ws['C37'].value
        AL=ws['C38'].value
        AM=ws['c39'].value
        AN=ws['c40'].value
        AO=ws['c41'].value
        AP=ws['C42'].value
        AQ=ws['C43'].value
        AR=ws['c44'].value
        AS=ws['c45'].value
        AT=ws['c46'].value
        AU=ws['C47'].value
        AV=ws['C48'].value
        AW=ws['c49'].value
        AX=ws['c50'].value
        AY=ws['c51'].value
        AZ=ws['C52'].value
        AAA=ws['C53'].value
        ABA=ws['c54'].value
        ACA=ws['c55'].value
        ADA=ws['c56'].value
        AEA=ws['C57'].value
        AFA=ws['C58'].value
        AGA=ws['c59'].value
        AHA=ws['c60'].value
        AIA=ws['c61'].value
        AJA=ws['C62'].value
        AKA=ws['C63'].value
        ALA=ws['c64'].value
        AMA=ws['c55'].value
        ANA=ws['c66'].value
        AOA=ws['C67'].value
        APA=ws['C68'].value
        AQA=ws['c69'].value
        ARA=ws['c70'].value
        ASA=ws['c71'].value
        ATA=ws['C72'].value
        AUA=ws['C73'].value
        AVA=ws['c74'].value
        AWA=ws['c75'].value
        AXA=ws['c76'].value
        AYA=ws['C77'].value
        AZA=ws['C78'].value
        AAB=ws['c79'].value
        AAC=ws['c80'].value
        AAD=ws['c81'].value
        AAE=ws['C82'].value
        AAF=ws['C83'].value
        AAG=ws['c84'].value
        AAH=ws['c85'].value
        AAI=ws['c86'].value
        AAJ=ws['C87'].value
        AAK=ws['C88'].value
        AAL=ws['c89'].value
        AAM=ws['c90'].value
        AAN=ws['c91'].value
        AAO=ws['C92'].value
        AAP=ws['C93'].value
        AAQ=ws['c94'].value
        AAR=ws['c95'].value
        AAS=ws['c96'].value
        AAT=ws['C97'].value
        AAU=ws['C98'].value
        AAV=ws['c99'].value
        AAY=ws['c100'].value
        pywhatkit.sendwhatmsg_instantly(A,Textoontem)
        pywhatkit.sendwhatmsg_instantly(B,Textoontem)
        pywhatkit.sendwhatmsg_instantly(C,Textoontem)
        pywhatkit.sendwhatmsg_instantly(D,Textoontem)
        pywhatkit.sendwhatmsg_instantly(E,Textoontem)
        pywhatkit.sendwhatmsg_instantly(F,Textoontem)
        pywhatkit.sendwhatmsg_instantly(G,Textoontem)
        pywhatkit.sendwhatmsg_instantly(H,Textoontem)
        pywhatkit.sendwhatmsg_instantly(I,Textoontem)
        pywhatkit.sendwhatmsg_instantly(J,Textoontem)
        pywhatkit.sendwhatmsg_instantly(K,Textoontem)
        pywhatkit.sendwhatmsg_instantly(L,Textoontem)
        pywhatkit.sendwhatmsg_instantly(M,Textoontem)
        pywhatkit.sendwhatmsg_instantly(N,Textoontem)
        pywhatkit.sendwhatmsg_instantly(O,Textoontem)
        pywhatkit.sendwhatmsg_instantly(P,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Q,Textoontem)
        pywhatkit.sendwhatmsg_instantly(R,Textoontem)
        pywhatkit.sendwhatmsg_instantly(S,Textoontem)
        pywhatkit.sendwhatmsg_instantly(T,Textoontem)
        pywhatkit.sendwhatmsg_instantly(U,Textoontem)
        pywhatkit.sendwhatmsg_instantly(V,Textoontem)
        pywhatkit.sendwhatmsg_instantly(W,Textoontem)
        pywhatkit.sendwhatmsg_instantly(X,Textoontem)
        pywhatkit.sendwhatmsg_instantly(Z,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AL,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AM,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AN,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AO,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AP,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ABA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ACA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ADA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AEA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AFA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AGA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AHA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AIA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AJA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AKA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ALA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AMA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ANA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AOA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(APA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AQA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ARA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ASA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(ATA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AUA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AVA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AWA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AXA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AYA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AZA,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAB,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAC,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAD,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAE,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAF,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAG,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAH,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAI,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAJ,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAK,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAR,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAS,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAT,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAU,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAV,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAW,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAX,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAY,Textoontem)
        pywhatkit.sendwhatmsg_instantly(AAZ,Textoontem)
@app.route("/excluirdb",methods=["POST"])
def excluir():
    if request.method =='POST':
        engine=sqlalchemy.create_engine("mysql+pymysql://root:Fepofepo123@127.0.0.1:3306/inicial")
        df= pd.read_sql_table("mensagemrapida", engine)
        query=f'''
            Truncate mensagemrapida; 
            
            '''
        df1=pd.read_sql_query(query, engine)
if  __name__=="__main__":
     app.run(debug=True)